exports.mongoConfig={
    cookieSecret:"blog",
    db:"liujinwei",
    host:"123.57.143.189",
    port:27017
};
exports.pagesize=2;
exports.categoryJson={
    "javascript":"javascript",
    "nodejs":"nodeJs",
    "notes":"随笔"
};